source 'https://github.com/CocoaPods/Specs.git'

target 'KRVideoPlayer', :exclusive => true do
  pod "KRVideoPlayer", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "KRVideoPlayer", :path => "../"

  
end
